# Generated by Django 4.1.2 on 2022-10-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdata",
            options={
                "verbose_name": "Информация о пользователе",
                "verbose_name_plural": "Информация о пользователях",
            },
        ),
    ]
