# Generated by Django 4.1.2 on 2022-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_userdata_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="apartment",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Номер квартиры"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="city",
            field=models.CharField(
                blank=True, default=None, max_length=30, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="house",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Номер дома"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=15,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="street",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, verbose_name="Улица"
            ),
        ),
    ]
